services:
  - type: web
    name: darktrace-backend
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm run serve
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
